name: ğŸš€ Deploy

on:
  push:
    branches:
      - 'develop'
    paths-ignore:
      - 'docs/**'

jobs:
  checks:
    name: âœ… Pre-deployment checks
    uses: ./.github/workflows/wk-checks.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  package:
    name: ğŸ“¦ï¸ Package app
    id: package
    needs: [ checks ]
    uses: ./.github/workflows/wk-package.yaml
    with:
      image-name: summit-backend
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    name: ğŸš€ Deploy
    needs: [ package ]
    uses: ./.github/workflows/wk-deploy.yaml
    with:
      image: ${{ vars.DOCKERHUB_USERNAME }}/summit-backend:${{ needs.package.outputs.version }}
